apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: pod-111-2
  name: pod-111-2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pod-111-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-111-2
    spec:
      nodeName: mu01
      containers:
        - image: dorowu/ubuntu-desktop-lxde-vnc:lastest
          imagePullPolicy: IfNotPresent
          name: ubuntu1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
#        - image: nginx
#          imagePullPolicy: IfNotPresent
#          name: ubunt2
#          resources: {}
#          terminationMessagePath: /dev/termination-log1
#          terminationMessagePolicy: File
#      nodeSelector:
#        label: mu01
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

