apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod1
  name: pod1
spec:
  containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:lastest
        imagePullPolicy: IfNotPresent
        name: ubuntu1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: ubuntu2
        resources: { }
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
